# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Github calculator program

on:
  workflow_dispatch:
    inputs:
      firstNumber:
        description: 'The first number to add'
        required: true
        type: string
      secondNumber:
        description: 'The second number to add'
        required: true
        type: string
        
jobs:
  run_calculator_program:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Run the program
      run: mvn compile exec:java -Dexec.mainClass="Main" -Dexec.args="${{ inputs.firstNumber }} ${{ inputs.secondNumber}}"
